# This is a basic workflow to help you get started with Actions

name: PR Arpa Infrastructure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: 
      - main
    paths:
      - 'terraform/azure/**'
      - 'test/'
      - '.github/workflows/pr-arpa-infrastructure.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Terraform format check
        id: tfformat
        run: terraform fmt -check -recursive
        
      - name: Comment Terraform results in PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: terraform-format-check
          message: |
            #### Terraform Format check: `${{ steps.tfformat.outcome }}`
            *Pusher: @${{ github.actor }}, Action: `${{ github.event_name }}`*
      
      - name: AZ login using Service Prinicipal
        shell: bash
        run: |
          az login -u ${{ env.SP_ID }} -p ${{ env.SP_PASSWD }}
          az account set -s ${{ env.SUBSCRIPTION_ID }}
          
      - name: Run Testcases
        shell: bash
        run: |
          echo "Running tests from $GITHUB_WORKSPACE/test"
          cd $GITHUB_WORKSPACE/test
          go test -v -timeout 30m 

      - name: Logout from Azure
        shell: bash
        run: az logout
